version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "IgrikXD"
    labels:
      - "CI/CD"
    commit-message:
      prefix: "Dependabot"