name: App build (Linux)

on:
  push:
    branches: [ "master" ]
    paths:
      - 'App/**'
  pull_request:
    branches: [ "**" ]
    paths:
      - 'App/**'
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  app-build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r App/requirements.txt
          pip install -r App/requirements-dev.txt

      - name: Build executable
        run: |
          cd App
          pyinstaller --noconsole --onefile \
            --add-data "beaconapp/ui/resources/*:ui/resources" \
            --exclude-module beaconapp.tests \
            --hidden-import PIL._tkinter_finder \
            --name BeaconApp beaconapp/main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: beaconapp-linux
          path: App/dist/BeaconApp
