name: App tests

on:
  push:
    branches: [ "master" ]
    paths:
      - 'App/**'
  pull_request:
    branches: [ "**" ]
    paths:
      - 'App/**'
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  app-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r App/requirements.txt
          pip install -r App/requirements-dev.txt

      - name: Run unit tests
        run: |
          cd App
          pytest -m unit -vv
