name: App tests

on:
  push:
    branches: [ "master" ]
    paths:
      - 'App/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'App/**'
  workflow_dispatch:

jobs:
  app-tests:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest==8.3.4

      - name: Run tests
        run: |
          pytest App -vv
