name: App build (Linux)

on:
  push:
    branches: [ "master" ]
    paths:
      - 'App/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'App/**'
  workflow_dispatch:

jobs:
  app-build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller==6.17.0
          cd App
          pip install -r requirements.txt

      - name: Build executable
        run: |
          pyinstaller --noconsole --onefile \
            --add-data "beaconapp/ui/resources/*:ui/resources" \
            --exclude-module beaconapp.tests \
            --hidden-import PIL._tkinter_finder \
            --name BeaconApp beaconapp/main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: beaconapp
          path: dist/BeaconApp.exe
