name: App build

on:
  workflow_run:
    workflows: ["App lint"]
    types:
      - completed
  workflow_dispatch:

jobs:
  app-build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller==6.11.1
          pip install -r App/requirements.txt

      - name: Build executable
        run: |
          pyinstaller --noconsole --onefile `
            --icon=App/beaconapp/ui/resources/beacon-app-logo.ico `
            --add-data "App/beaconapp/ui/resources/*;ui/resources" `
            --name BeaconApp `
            App/beaconapp/main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: beaconapp
          path: dist/BeaconApp.exe
