name: Firmware build

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Firmware/**/*.ino'
      - 'Firmware/**/*.yml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'Firmware/**/*.ino'
      - 'Firmware/**/*.yml'
  workflow_dispatch:

jobs:
  firmware-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Firmware build
        run: |
          for d in Firmware/*/; do
            echo "Compiling $d"
            arduino-cli compile \
              --export-binaries \
              "$d"
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-firmware
          path: |
            **/*.hex
            **/*.elf
