name: Firmware build (ATmega328P-based)

on:
  push:
    branches: [ "**" ]
    paths:
      - 'Firmware/ATmega328P-based/**/*.ino'
      - 'Firmware/ATmega328P-based/**/*.yml'
  pull_request:
    branches: [ "**" ]
    paths:
      - 'Firmware/ATmega328P-based/**/*.ino'
      - 'Firmware/ATmega328P-based/**/*.yml'
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  firmware-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Firmware build
        run: |
          for d in Firmware/ATmega328P-based/*/; do
            echo "Compiling $d"
            arduino-cli compile \
              --export-binaries \
              "$d"
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-firmware
          path: |
            **/*.hex
            **/*.elf
